### PR TITLE
Add IOFlatList and withIOFlatlist

### PR DESCRIPTION
**Pull request by JensonMiralles**
## Changes
- Support FlatList in IntersectionObserver

### CODE REVIEW

**Comment by zhbhun** [comment]
Consider adding IOFlatList, for temporary use refer to the following issue

https://github.com/zhbhun/react-native-intersection-observer/issues/3#issuecomment-922475808

**Comment by xgenem** [comment]
> Consider adding IOFlatList, for temporary use refer to the following issue
> 
> [#3 (comment)](https://github.com/zhbhun/react-native-intersection-observer/issues/3#issuecomment-922475808)

This completely defeats the purpose of a FlatList.

**Comment by zhbhun** [comment]
Sorry, I didn't understand what you said. What principles does it defeats?

**Comment by zhbhun** [comment]
FlatList is now supported in 0.2.0.

**Pull request closed without merging**
